### ISSUE TITLE
Add configurable predefined variables

### ISSUE THREAD

**Issue by mMontu** [arecarn/crunch.vim#28]
The plugin could have a mechanism to define constant values/aliases to functions which it would replace when parsing the expression.

I thought of two main uses:

* Constants: despite it is possible to write down the constant before starting the calculation, it could be helpful to have common constants defined on .vimrc and always available to all crunch calculations

* aliases: 
    `{1}**{2} : pow({1}, {2})`
    `then x**y would be the same as pow(x, y)`

Just an idea, maybe it is out of the scope for the plugin.

**Comment by arecarn** [comment]
Finally got this added in

**Comment by mMontu** [comment]
Hello Ryan! Sorry for the long delay

It has been a while since I last bothered you about this plugin :)
I noticed you made very large changes, including the test framework. I have heard about the Vader plugin, but never tried it -- is it easy to try it?

Keep up the good work

**Comment by arecarn** [comment]
Hey Marcelo,

Vader is pretty easy to use.

For a short way to run all the tests for cruch you could do something like this (as long as you are in crunch tests directory, with vader installed)
```
vim -c 'Vader! *.vader'
```
Vader isn't as flexible as runVimTests, but I find it easier to work with.
