### ISSUE TITLE
Append result after = at the end of expression else replace it.

### ISSUE THREAD

**Issue by denius** [arecarn/crunch.vim#48]
With hotkeys `g={motion}` and `g==` there is either replace or append expressions depended on `g:crunch_result_type_append`.
It would be nice to have option to append result to expression ended with `=` and replace one without last `=`.
It may be new option `g:crunch_result_type_append = 2` to preserve compatibility with exist installations.

**Comment by arecarn** [comment]
I like the idea, It might be a while, but I'll look into doing this or something similar.

**Comment by arecarn** [comment]
This should be implemented now let me know if you find anything wrong with it.
