### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by dendeffe** [arecarn/crunch.vim#49]
Is there a way to round results (e.g. ceil, round etc.)

**Comment by arecarn** [comment]
`ceil()` and `round()` should work since they are built in vimscript functions. Let me know if you run into any issues using them. 

see `:help ceil()` or `:help round()` for more info about them.

**Comment by dendeffe** [comment]
Yes, seems to work now. Strange. Thanks for following up.

**Comment by arecarn** [comment]
No problem, glad to hear it.
