### ISSUE TITLE
Exponent notation not recognized

### ISSUE THREAD

**Issue by cizmazia** [arecarn/crunch.vim#52]
Vjg= evaluation of the visually selected 2 lines below does not recognize the exponent notation

n = 2.304e7
n/10 = Crunch error: value for e7 not found

g== on the second line produces the correct result:

n/10 = 2304000

**Comment by arecarn** [comment]
Good catch! I'll see what I can do.

**Comment by arecarn** [comment]
I've added a fix let me know if this fixes your problem.

**Comment by cizmazia** [comment]
Thanks! It works fine.
